kind: Deployment
apiVersion: apps/v1
metadata:
   name: abdallah
spec:
   replicas: 2
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     app: abdallah
   template:
      metadata:
        labels:
          app: abdallah
      spec:
       containers:
        - name: abdallah
          image: abdallahdoc/django-ecom-app
          imagePullPolicy: Always
          ports:
          - containerPort: 8000
