kind: Service                             
apiVersion: v1
metadata:
  name: abdallah
  labels:
    app: abdallah
spec:
  ports:
    - port: 8000                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: abdallah                    
  type: LoadBalancer                   
